# Generated by Django 5.2.12 on 2026-03-14 16:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("consumo", "Consumo"), ("tecnica", "Técnica")],
                        max_length=20,
                    ),
                ),
                ("is_reportable", models.BooleanField()),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
                "ordering": ["name"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("is_reportable", True), ("kind", "consumo")),
                            models.Q(("is_reportable", False), ("kind", "tecnica")),
                            _connector="OR",
                        ),
                        name="category_kind_is_reportable_consistente",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MerchantMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("merchant_norm", models.CharField(max_length=255)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("seed", "Base inicial"),
                            ("manual_review", "Revisão manual"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="merchant_maps",
                        to="classification.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mapa de merchant",
                "verbose_name_plural": "Mapas de merchant",
                "ordering": ["merchant_norm"],
            },
        ),
        migrations.CreateModel(
            name="ReviewQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("low_confidence", "Baixa confiança"),
                            ("conflict", "Conflito"),
                            ("no_match", "Sem correspondência"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("resolved", "Resolvida"),
                            ("ignored", "Ignorada"),
                        ],
                        max_length=20,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "suggested_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review_suggestions",
                        to="classification.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fila de revisão",
                "verbose_name_plural": "Fila de revisão",
                "ordering": ["status", "-created_at"],
            },
        ),
    ]
