# Generated by Django 5.2.12 on 2026-03-31 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classification", "0001_initial"),
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewqueue",
            name="transaction",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_queue",
                to="transactions.transaction",
            ),
        ),
        migrations.AddConstraint(
            model_name="merchantmap",
            constraint=models.UniqueConstraint(
                fields=("merchant_norm", "category"), name="uniq_merchant_norm_category"
            ),
        ),
    ]
