# Generated by Django 5.2.12 on 2026-04-18 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationRuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativo'), ('archived', 'Arquivado')], default='draft', max_length=20)),
                ('yaml_content', models.TextField('conteudo YAML', blank=True)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('validation_errors', models.TextField(blank=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-version', '-updated_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('status',), name='uniq_active_classification_ruleset')],
            },
        ),
    ]
