# Generated by Django 5.2.12 on 2026-03-14 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("extrato_conta_nubank", "Extrato conta Nubank"),
                            ("fatura_cartao_nubank", "Fatura cartão Nubank"),
                            ("extrato_conta_itau", "Extrato conta Itaú"),
                            ("fatura_cartao_itau", "Fatura cartão Itaú"),
                        ],
                        max_length=40,
                    ),
                ),
                ("source_filename", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Recebido"),
                            ("processed", "Processado"),
                            ("partial", "Parcial"),
                            ("failed", "Falhou"),
                        ],
                        max_length=20,
                    ),
                ),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("imported_rows", models.PositiveIntegerField(default=0)),
                ("duplicated_rows", models.PositiveIntegerField(default=0)),
                ("imported_at", models.DateTimeField()),
                ("error_log", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_batches",
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lote de importação",
                "verbose_name_plural": "Lotes de importação",
                "ordering": ["-imported_at", "-id"],
            },
        ),
    ]
