# Generated by Django 5.2.12 on 2026-04-01 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="importbatch",
            name="file",
            field=models.FileField(blank=True, upload_to="imports/csv/"),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="reference_month",
            field=models.DateField(
                blank=True,
                help_text="Use o primeiro dia do mês de referência (ex.: 2026-04-01).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="rows_imported",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="rows_skipped",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="rows_total",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="importbatch",
            name="source_filename",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="importbatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("received", "Recebido"),
                    ("processed", "Processado"),
                    ("partial", "Parcial"),
                    ("failed", "Falhou"),
                ],
                default="received",
                max_length=20,
            ),
        ),
    ]
