# Generated by Django 5.2.12 on 2026-03-14 16:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("classification", "0001_initial"),
        ("imports", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_date", models.DateField()),
                ("description_raw", models.TextField()),
                ("description_norm", models.TextField()),
                ("merchant_norm", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="BRL", max_length=3)),
                (
                    "direction",
                    models.CharField(
                        choices=[("debit", "Débito"), ("credit", "Crédito")],
                        max_length=10,
                    ),
                ),
                ("raw_hash", models.CharField(max_length=64)),
                (
                    "classification_source",
                    models.CharField(
                        choices=[
                            ("merchant_map", "Merchant map"),
                            ("rule", "Regra"),
                            ("similarity", "Similaridade"),
                            ("manual", "Manual"),
                            ("unclassified", "Não classificada"),
                        ],
                        default="unclassified",
                        max_length=20,
                    ),
                ),
                ("posted_date", models.DateField(blank=True, null=True)),
                (
                    "classification_confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("is_installment", models.BooleanField(blank=True, null=True)),
                (
                    "installment_current",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "installment_total",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("installment_key", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="accounts.account",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="classification.category",
                    ),
                ),
                (
                    "import_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="imports.importbatch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transação",
                "verbose_name_plural": "Transações",
                "ordering": ["-transaction_date", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account", "raw_hash"),
                        name="transaction_account_raw_hash_unico",
                    )
                ],
            },
        ),
    ]
