# Generated by Django 5.2.12 on 2026-04-02 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="merchant_raw",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
