# Generated by Django 5.2.12 on 2026-04-06 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("classification", "0002_initial"),
        ("imports", "0002_importbatch_file_importbatch_reference_month_and_more"),
        ("transactions", "0002_transaction_merchant_raw"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="external_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id__isnull", False)),
                fields=("account", "external_id"),
                name="uniq_transaction_account_external_id",
            ),
        ),
    ]
