# Generated by Django 5.2.12 on 2026-04-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("classification", "0002_initial"),
        ("imports", "0002_importbatch_file_importbatch_reference_month_and_more"),
        ("transactions", "0003_transaction_external_id_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="transaction",
            name="uniq_transaction_account_raw_hash",
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id__isnull", True)),
                fields=("account", "raw_hash"),
                name="uniq_transaction_account_raw_hash",
            ),
        ),
    ]
