# Generated by Django 5.2.12 on 2026-04-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("classification", "0002_initial"),
        ("imports", "0002_importbatch_file_importbatch_reference_month_and_more"),
        (
            "transactions",
            "0004_remove_transaction_uniq_transaction_account_raw_hash_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="transaction",
            name="uniq_transaction_account_external_id",
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id__isnull", False)),
                fields=("account", "external_id", "raw_hash"),
                name="uniq_transaction_account_external_id_raw_hash",
            ),
        ),
    ]
