# Generated by Django 5.2.12 on 2026-03-14 16:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classification", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_month",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use o formato YYYY-MM.",
                                regex="^\\d{4}-(0[1-9]|1[0-2])$",
                            )
                        ],
                    ),
                ),
                (
                    "planned_amount",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="budgets",
                        to="classification.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orçamento",
                "verbose_name_plural": "Orçamentos",
                "ordering": ["-period_month", "category__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("period_month", "category"),
                        name="budget_period_month_category_unico",
                    )
                ],
            },
        ),
    ]
